version: '3.4'

services:
  pegel:
    image: pegel
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - MQTT_SERVER=Your_mqtt_ip
      - MQTT_USER=your_mqtt_Username
      - MQTT_PASSWORD=your_mqtt_Password
